stages:
  - ci
  - cd

build:
  tags:
    - st13-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: ci
  script:
    scala-cli compile .

test:
  allow_failure: true
  tags:
    - st13-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: ci
  needs:
    - build
  script:
    scala-cli test .

docker-build:
  tags:
    - st13-runner
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: ci
  needs: 
    - test
  script:
    - sudo scala-cli package 
      --docker src/main/scala/timeserver/Main.scala 
      --docker-from openjdk:17 
      --docker-image-repository timeserver
      --docker-image-tag latest

docker-publish:
  tags:
      - st13-runner
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: ci
  needs: 
    - docker-build
  script: sudo docker push nikololiahim/timeserver:latest
